# Archivo: netlify.toml
# Configuración final y correcta. Esta será la única fuente de verdad.

[build]
  # El punto de partida es la carpeta 'frontend'
  base = "frontend"
  
  # El comando para construir el sitio
  command = "npm run build"
  
  # La carpeta de salida, relativa a 'base'. (frontend/build)
  publish = "build"

# La carpeta de funciones, relativa a la raíz del repositorio.
# Esta es la configuración correcta para tu nueva estructura.
[functions]
  directory = "netlify/functions"
  
# Configuración para desarrollo local
[dev]
  command = "npm start --prefix frontend"
  port = 8888
  targetPort = 3000
  functions = "frontend/netlify/functions"