# Archivo: netlify.toml
# Configuración final y explícita para Build y Functions.

# --- BLOQUE DE BUILD ---
# Esto le dice a Netlify cómo construir tu frontend de React.
[build]
  base    = "frontend"
  command = "npm run build"
  publish = "build"

# --- BLOQUE DE FUNCTIONS (MÁS EXPLÍCITO) ---
# Esto le dice a Netlify dónde están tus funciones serverless,
# sin ambigüedad y relativo a la raíz del repositorio.
[functions]
  directory = "netlify/functions"

# --- BLOQUE DE DESARROLLO LOCAL ---
# Esto no cambia, es para que 'netlify dev' funcione.
[dev]
  command = "npm start --prefix frontend"
  port = 8888
  targetPort = 3000