# Archivo: /netlify.toml

# Configuración de Build
[build]
  # Directorio que Netlify usará para desplegar tu frontend
  publish = "frontend/build"
  # Directorio donde Netlify buscará tus funciones serverless
  functions = "netlify/functions"

# Configuración para el desarrollo local con 'netlify dev'
[dev]
  # Comando para iniciar tu app de React
  command = "npm start --prefix frontend"
  # Puerto donde se ejecutará el entorno completo de Netlify
  port = 8888
  # Puerto en el que corre tu app de React
  targetPort = 3000